global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    filename: "/etc/traefik/dynamic_conf.yml"
  docker:
    exposedByDefault: false

api:
  dashboard: true
  insecure: true
